<?php
// Traductions françaises
return [
    // Navigation
    'nav_login' => 'Se connecter',
    'nav_submit_claim' => 'Soumettre une Réclamation',
    'nav_logout' => 'Déconnexion',
    'nav_profile' => 'Mon profil',
    'nav_notifications' => 'Notifications',
    'nav_dashboard' => 'Tableau de bord',
    'nav_hello' => 'Bonjour',
    
    // Page d'accueil
    'home_title' => 'Resolve',
    'home_subtitle' => 'Plateforme Intelligente de Gestion des Réclamations',
    'home_description' => 'Résolvez vos problèmes rapidement et efficacement avec notre plateforme moderne',
    'home_get_started' => 'Commencer',
    'home_learn_more' => 'En savoir plus',
    'home_hero_badge' => 'Portail de Services & Support Interne',
    'home_hero_title_1' => 'IT, RH, Services Généraux.',
    'home_hero_title_2' => 'Une seule interface pour',
    'home_hero_title_highlight' => 'toutes vos demandes.',
    'home_hero_description' => 'Centralisez vos signalements d\'incidents techniques et vos requêtes administratives. Suivez leur résolution en temps réel auprès des services concernés.',
    'home_hero_cta_submit' => 'Déposer votre Réclamation',
    'home_hero_cta_login' => 'Espace Utilisateur',
    'home_features_title' => 'Pourquoi centraliser',
    'home_features_title_highlight' => 'vos demandes ici ?',
    'home_features_subtitle' => 'Un outil interne pour simplifier vos signalements et suivre leur traitement en toute transparence',

    'home_feature_1_title' => 'Soumission Simplifiée',
    'home_feature_1_desc' => 'Plus besoin d\'envoyer des emails perdus. Signalez une panne informatique ou une erreur administrative en 2 minutes grâce aux formulaires dédiés.',
    'home_feature_2_title' => 'Traçabilité Complète',
    'home_feature_2_desc' => 'De la "Prise en compte" à la "Résolution", sachez exactement quel département (IT, Compta, RH) traite votre dossier.',

    'home_feature_3_title' => 'Notifications Intelligentes',
    'home_feature_3_desc' => 'Recevez des alertes automatiques à chaque changement de statut. Ne manquez aucune mise à jour importante.',
    'home_feature_4_title' => 'Espace Gestionnaire',
    'home_feature_4_desc' => 'Tableaux de bord avancés avec analytics en temps réel pour une gestion efficace et des prises de décisions éclairées.',
    'home_cta_title' => 'Prêt à Commencer ?',
    'home_cta_description' => 'Rejoignez des centaines d\'organisations qui font confiance à notre plateforme pour gérer leurs réclamations efficacement.',
    'home_cta_submit' => 'Soumettre une Réclamation',
    'home_cta_register' => 'Créer un Compte',
    'home_footer_description' => 'Outil interne de gestion des incidents et demandes collaborateurs.',

    'home_footer_quick_links' => 'Liens Rapides',
    'home_footer_submit_claim' => 'Soumettre Réclamation',
    'home_footer_login' => 'Se Connecter',
    'home_footer_register' => 'S\'Inscrire',
    'home_footer_support' => 'Support',
    'home_footer_email' => 'support@resolve.app',
    'home_footer_phone' => '+212 XXX-XXXX',
    'home_footer_copyright' => 'Tous droits réservés',
    
    // Features
    'feature_fast' => 'Rapide',
    'feature_fast_desc' => 'Traitement rapide de vos réclamations',
    'feature_secure' => 'Sécurisé',
    'feature_secure_desc' => 'Vos données sont protégées',
    'feature_tracking' => 'Suivi en temps réel',
    'feature_tracking_desc' => 'Suivez l\'état de vos réclamations',
    
    // Authentification
    'login_title' => 'Connexion',
    'login_subtitle' => 'Accédez à votre espace',
    'login_button' => 'Se connecter',
    'register_title' => 'Inscription',
    'register_subtitle' => 'Rejoignez notre plateforme',
    'register_button' => 'S\'inscrire',
    'email' => 'Adresse Email',
    'password' => 'Mot de passe',
    'confirm_password' => 'Confirmer le mot de passe',
    'name' => 'Nom',
    'full_name' => 'Nom complet',
    'first_name' => 'Prénom',
    'forgot_password' => 'Mot de passe oublié ?',
    'no_account' => 'Pas encore de compte ?',
    'create_account' => 'Créer un compte',
    'register_here' => 'Inscrivez-vous ici',
    'already_account' => 'Déjà un compte ?',
    'login_here' => 'Connectez-vous ici',
    'login_now' => 'Se connecter maintenant',
    'back_home' => 'Retour à l\'accueil',
    'show_hide_password' => 'Afficher / masquer le mot de passe',
    'password_strength' => 'Force du mot de passe',
    'password_hint' => 'Au moins 6 caractères',
    'fill_all_fields' => 'Veuillez remplir tous les champs.',
    'invalid_credentials' => 'Email ou mot de passe incorrect.',
    'passwords_not_match' => 'Les mots de passe ne correspondent pas.',
    'password_min_length' => 'Le mot de passe doit contenir au moins 6 caractères.',
    'email_exists' => 'Cette adresse email est déjà utilisée.',
    'registration_success' => 'Inscription réussie ! Vous pouvez maintenant vous connecter.',
    'registration_error' => 'Une erreur est survenue lors de l\'inscription.',
    
    // Showcase section
    'showcase_badge' => 'Sécurisé & Moderne',
    'showcase_badge_register' => 'Simple & Efficace',
    'showcase_title' => 'Portail Support & Services',
    'showcase_title_register' => 'Créez votre compte en quelques secondes',
    'showcase_feature_1' => 'Suivez vos réclamations en temps réel et recevez des mises à jour.',
    'showcase_feature_2' => 'Interface épurée, rapide et accessible sur tous les appareils.',
    'showcase_feature_3' => 'Données protégées avec chiffrement et bonnes pratiques.',
    'showcase_feature_register_1' => 'Notifications claires sur l\'état de vos réclamations.',
    'showcase_feature_register_2' => 'Historique et détails accessibles à tout moment.',
    'showcase_feature_register_3' => 'Design soigné pour une expérience confortable.',
    'showcase_chip_security' => 'Sécurité',
    'showcase_chip_fast' => 'Rapide',
    'showcase_chip_secure' => 'Sécurisé',
    'showcase_chip_responsive' => 'Responsive',
    'showcase_chip_user_check' => 'Rapide',
    
    // Dashboard
    'dashboard_title' => 'Tableau de Bord',
    'dashboard_area_claimant' => 'Mon Espace Support',
    'my_claims' => 'Mes Demandes',
    'total_claims' => 'Total Demandes',
    'pending_claims' => 'En traitement',
    'resolved_claims' => 'Résolus',
    'closed_claims' => 'Fermées',
    'new_claim' => 'Nouvelle Demande',
    'my_profile' => 'Mon profil',
    'notifications' => 'Notifications',
    'no_notifications' => 'Aucune notification',
    'see_all_notifications' => 'Voir toutes les notifications',
    'logout' => 'Déconnexion',
    'hello' => 'Bonjour',
    'just_now' => 'À l\'instant',
    'minutes_ago' => 'min',
    'hours_ago' => 'h',
    'days_ago' => 'j',
    'search_claim' => '🔍 Rechercher une demande...',
    
    // Réclamations
    'claim_subject' => 'Sujet',
    'claim_description' => 'Description',
    'claim_category' => 'Catégorie',
    'claim_status' => 'Statut',
    'claim_date' => 'Date',
    'claim_actions' => 'Actions',
    'claim_action' => 'Action',
    'claim_details' => 'Détails de la demande',
    'claim_submit' => 'Soumettre une demande',
    'claim_new' => 'Nouvelle demande',
    'claim_history' => 'Mes Demandes',
    'claim_no_subject' => 'Sans sujet',
    'claim_none_found' => 'Aucune demande trouvée',
    
    // Statuts
    'status_pending' => 'En attente',
    'status_in_progress' => 'En cours',
    'status_resolved' => 'Traitée',
    'status_closed' => 'Fermée',
    'status_accepted' => 'Acceptée',
    'status_awaiting_info' => 'En attente info',
    'status_processing' => 'En cours de traitement',
    
    // Actions
    'view' => 'Voir',
    'edit' => 'Modifier',
    'delete' => 'Supprimer',
    'submit' => 'Soumettre',
    'cancel' => 'Annuler',
    'save' => 'Enregistrer',
    'save_changes' => 'Enregistrer les modifications',
    'back' => 'Retour',
    'back_to_dashboard' => 'Retour au tableau de bord',
    'search' => 'Rechercher',
    'filter' => 'Filtrer',
    'reset' => 'Réinitialiser',
    'close' => 'Fermer',
    'add_comment' => 'Ajouter un commentaire',
    'send' => 'Envoyer',
    'attach_file' => 'Joindre un fichier',
    'optional' => 'Optionnel',
    'required' => 'Obligatoire',
    
    // Détails de réclamation
    'claim_detail_title' => 'Détails de la Réclamation',
    'claim_info' => 'Informations',
    'submitted_on' => 'Soumis le',
    'last_update' => 'Dernière mise à jour',
    'current_status' => 'Statut actuel',
    'full_description' => 'Description complète',
    'attached_file' => 'Fichier joint',
    'download' => 'Télécharger',
    'comments_history' => 'Historique des commentaires',
    'no_comments' => 'Aucun commentaire pour le moment',
    'your_comment' => 'Votre commentaire',
    'comment_placeholder' => 'Écrivez votre commentaire ici...',
    'claim_closed_no_comment' => 'Cette réclamation est fermée. Vous ne pouvez plus ajouter de commentaires.',
    'by' => 'par',
    'you' => 'Vous',
    'manager' => 'Gestionnaire',
    'admin' => 'Administrateur',
    
    // Notifications
    'notifications_title' => 'Notifications',
    'mark_all_read' => 'Tout marquer comme lu',
    'mark_as_read' => 'Marquer comme lu',
    'unread' => 'Non lu',
    'read' => 'Lu',
    'new_comment' => 'Nouveau commentaire',
    'status_changed' => 'Changement de statut',
    'claim_assigned' => 'Réclamation assignée',
    'claim_closed' => 'Réclamation fermée',
    'notif_status_changed_title' => 'Statut changé',
    'notif_status_changed_message' => 'Le statut de votre réclamation est maintenant',
    'notif_comment_added_title' => 'Nouveau commentaire',
    'status_soumis' => 'Soumis',
    'status_en_cours' => 'En cours',
    'status_en_cours_de_traitement' => 'En traitement',
    'status_en_attente' => 'En attente',
    'status_resolu' => 'Résolu',
    'status_rejete' => 'Rejeté',
    'status_archive' => 'Archivé',
    'status_traite' => 'Traité',
    'status_ferme' => 'Fermé',
    'status_attente_info' => 'Attente d\'info',
    'your_claim' => 'Votre réclamation',
    'notif_comment_added_message' => 'Un nouveau commentaire a été ajouté à votre réclamation',
    'system_status_change_comment' => 'Le statut a été changé en',
    'no_notifications_yet' => 'Aucune notification pour le moment',
    'stay_tuned' => 'Vous serez notifié de toute mise à jour concernant vos réclamations.',
    'notif_see_all' => 'Voir toutes les notifications',
    'notif_no_notifications' => 'Aucune notification',
    
    // Profil
    'profile_title' => 'Mon Profil',
    'personal_info' => 'Informations personnelles',
    'account_security' => 'Sécurité du compte',
    'first_name' => 'Prénom',
    'last_name' => 'Nom',
    'email_address' => 'Adresse email',
    'current_password' => 'Mot de passe actuel',
    'new_password' => 'Nouveau mot de passe',
    'confirm_new_password' => 'Confirmer le nouveau mot de passe',
    'update_profile' => 'Mettre à jour le profil',
    'update_password' => 'Modifier le mot de passe',
    'profile_updated' => 'Profil mis à jour avec succès !',
    'password_updated' => 'Mot de passe modifié avec succès !',
    'all_fields_required' => 'Tous les champs sont obligatoires.',
    'email_invalid' => 'L\'adresse email n\'est pas valide.',
    'email_already_used' => 'Cette adresse email est déjà utilisée.',
    'password_incorrect' => 'Le mot de passe actuel est incorrect.',
    'update_error' => 'Erreur lors de la mise à jour.',
    
    // Soumission
    'submit_claim_title' => 'Nouvelle Réclamation',
    'claim_form' => 'Formulaire de réclamation',
    'subject' => 'Objet de la réclamation',
    'subject_placeholder' => 'Ex: Problème de connexion...',
    'category' => 'Catégorie',
    'select_category' => 'Sélectionnez une catégorie',
    'choose_category' => 'Choisir une catégorie...',
    'description' => 'Description détaillée',
    'description_placeholder' => 'Décrivez votre problème en détail...',
    'supporting_document' => 'Pièce jointe',
    'click_to_upload' => 'Cliquez pour télécharger',
    'or_drag_drop' => 'ou glissez-déposez',
    'file_types_max_size' => 'JPG, PNG, PDF, DOC (Max 5 Mo)',
    'view_my_claims' => 'Voir mes réclamations',
    'error_occurred' => 'Une erreur est survenue',
    'supporting_document_help' => 'Formats acceptés : PDF, JPG, PNG, DOCX (max 5MB)',
    'choose_file' => 'Choisir un fichier',
    'no_file_chosen' => 'Aucun fichier choisi',
    'submit_claim_button' => 'Soumettre la réclamation',
    'claim_submitted' => 'Réclamation soumise avec succès !',
    'claim_number' => 'Numéro de réclamation',
    'claim_tracked' => 'Vous pouvez suivre son évolution dans votre tableau de bord.',
    'submit_another' => 'Soumettre une autre réclamation',
    'fill_required_fields' => 'Veuillez remplir tous les champs obligatoires.',
    'file_too_large' => 'Le fichier est trop volumineux (max 5MB).',
    'invalid_file_type' => 'Type de fichier non autorisé.',
    
    // Messages
    'success' => 'Succès',
    'error' => 'Erreur',
    'warning' => 'Attention',
    'info' => 'Information',
    'no_results' => 'Aucun résultat',
    'loading' => 'Chargement...',
    
    // Suppression
    'delete' => 'Supprimer',
    'delete_confirm' => 'Êtes-vous sûr de vouloir supprimer cette réclamation ? Cette action est irréversible.',
    'claim_deleted_success' => 'Réclamation supprimée avec succès',
    'error_delete_failed' => 'Erreur lors de la suppression',
    'error_claim_not_found' => 'Réclamation introuvable',
    'error_unauthorized' => 'Vous n\'êtes pas autorisé à supprimer cette réclamation',
    'error_invalid_request' => 'Requête invalide',
    
    // Footer
    'footer_rights' => 'Tous droits réservés',
    'footer_contact' => 'Contact',
    'footer_about' => 'À propos',
    'footer_terms' => 'Conditions d\'utilisation',
    'footer_privacy' => 'Politique de confidentialité',
];
