<?php
// English translations
return [
    // Navigation
    'nav_login' => 'Login',
    'nav_submit_claim' => 'Submit a Claim',
    'nav_logout' => 'Logout',
    'nav_profile' => 'My Profile',
    'nav_notifications' => 'Notifications',
    'nav_dashboard' => 'Dashboard',
    'nav_hello' => 'Hello',
    
    // Homepage
    'home_title' => 'Resolve',
    'home_subtitle' => 'Intelligent Complaint Management Platform',
    'home_description' => 'Resolve your issues quickly and efficiently with our modern platform',
    'home_get_started' => 'Get Started',
    'home_learn_more' => 'Learn More',
    'home_hero_badge' => 'Internal Services & Support Portal',
    'home_hero_title_1' => 'IT, HR, General Services.',
    'home_hero_title_2' => 'One interface for',
    'home_hero_title_highlight' => 'all your requests.',
    'home_hero_description' => 'Centralize your technical incident reports and administrative requests. Track their resolution in real-time with the concerned departments.',
    'home_hero_cta_submit' => 'Submit Your Claim',
    'home_hero_cta_login' => 'User Portal',
    'home_features_title' => 'Why centralize',
    'home_features_title_highlight' => 'your requests here?',
    'home_features_subtitle' => 'An internal tool to simplify your reports and track their processing with complete transparency',

    'home_feature_1_title' => 'Simplified Submission',
    'home_feature_1_desc' => 'No more lost emails. Report an IT issue or administrative error in 2 minutes using dedicated forms.',
    'home_feature_2_title' => 'Complete Traceability',
    'home_feature_2_desc' => 'From "Acknowledged" to "Resolved", know exactly which department (IT, Accounting, HR) is handling your request.',

    'home_feature_3_title' => 'Smart Notifications',
    'home_feature_3_desc' => 'Receive automatic alerts with every status change. Never miss an important update.',
    'home_feature_4_title' => 'Manager Portal',
    'home_feature_4_desc' => 'Advanced dashboards with real-time analytics for efficient management and informed decision-making.',
    'home_cta_title' => 'Ready to Get Started?',
    'home_cta_description' => 'Join hundreds of organizations that trust our platform to manage their complaints effectively.',
    'home_cta_submit' => 'Submit a Claim',
    'home_cta_register' => 'Create an Account',
    'home_footer_description' => 'Internal tool for managing employee incidents and requests.',

    'home_footer_quick_links' => 'Quick Links',
    'home_footer_submit_claim' => 'Submit Claim',
    'home_footer_login' => 'Login',
    'home_footer_register' => 'Register',
    'home_footer_support' => 'Support',
    'home_footer_email' => 'support@resolve.app',
    'home_footer_phone' => '+212 XXX-XXXX',
    'home_footer_copyright' => 'All rights reserved',
    
    // Features
    'feature_fast' => 'Fast',
    'feature_fast_desc' => 'Quick processing of your claims',
    'feature_secure' => 'Secure',
    'feature_secure_desc' => 'Your data is protected',
    'feature_tracking' => 'Real-time Tracking',
    'feature_tracking_desc' => 'Track the status of your claims',
    
    // Authentication
    'login_title' => 'Login',
    'login_subtitle' => 'Access your account',
    'login_button' => 'Sign in',
    'register_title' => 'Register',
    'register_subtitle' => 'Join our platform',
    'register_button' => 'Sign up',
    'email' => 'Email Address',
    'password' => 'Password',
    'confirm_password' => 'Confirm Password',
    'name' => 'Name',
    'full_name' => 'Full Name',
    'first_name' => 'First Name',
    'forgot_password' => 'Forgot password?',
    'no_account' => 'Don\'t have an account yet?',
    'create_account' => 'Create an account',
    'register_here' => 'Register here',
    'already_account' => 'Already have an account?',
    'login_here' => 'Login here',
    'login_now' => 'Login now',
    'back_home' => 'Back to home',
    'show_hide_password' => 'Show / hide password',
    'password_strength' => 'Password strength',
    'password_hint' => 'At least 6 characters',
    'fill_all_fields' => 'Please fill in all fields.',
    'invalid_credentials' => 'Invalid email or password.',
    'passwords_not_match' => 'Passwords do not match.',
    'password_min_length' => 'Password must be at least 6 characters.',
    'email_exists' => 'This email address is already in use.',
    'registration_success' => 'Registration successful! You can now log in.',
    'registration_error' => 'An error occurred during registration.',
    
    // Showcase section
    'showcase_badge' => 'Secure & Modern',
    'showcase_badge_register' => 'Simple & Effective',
    'showcase_title' => 'Support & Services Portal',
    'showcase_title_register' => 'Create your account in seconds',
    'showcase_feature_1' => 'Track your claims in real-time and receive updates.',
    'showcase_feature_2' => 'Clean interface, fast and accessible on all devices.',
    'showcase_feature_3' => 'Protected data with encryption and best practices.',
    'showcase_feature_register_1' => 'Clear notifications about the status of your claims.',
    'showcase_feature_register_2' => 'History and details accessible at any time.',
    'showcase_feature_register_3' => 'Polished design for a comfortable experience.',
    'showcase_chip_security' => 'Security',
    'showcase_chip_fast' => 'Fast',
    'showcase_chip_secure' => 'Secure',
    'showcase_chip_responsive' => 'Responsive',
    'showcase_chip_user_check' => 'Fast',
    
    // Dashboard
    'dashboard_title' => 'Dashboard',
    'dashboard_area_claimant' => 'My Support Portal',
    'my_claims' => 'My Requests',
    'total_claims' => 'Total Requests',
    'pending_claims' => 'In Progress',
    'resolved_claims' => 'Resolved',
    'closed_claims' => 'Closed',
    'new_claim' => 'New Request',
    'my_profile' => 'My Profile',
    'notifications' => 'Notifications',
    'no_notifications' => 'No notifications',
    'see_all_notifications' => 'See all notifications',
    'logout' => 'Logout',
    'hello' => 'Hello',
    'just_now' => 'Just now',
    'minutes_ago' => 'min',
    'hours_ago' => 'h',
    'days_ago' => 'd',
    'search_claim' => '🔍 Search for a request...',
    
    // Claims
    'claim_subject' => 'Subject',
    'claim_description' => 'Description',
    'claim_category' => 'Category',
    'claim_status' => 'Status',
    'claim_date' => 'Date',
    'claim_actions' => 'Actions',
    'claim_action' => 'Action',
    'claim_details' => 'Request details',
    'claim_submit' => 'Submit a request',
    'claim_new' => 'New request',
    'claim_history' => 'My Requests',
    'claim_no_subject' => 'No subject',
    'claim_none_found' => 'No requests found',
    
    // Status
    'status_pending' => 'Pending',
    'status_in_progress' => 'In Progress',
    'status_resolved' => 'Resolved',
    'status_closed' => 'Closed',
    'status_accepted' => 'Accepted',
    'status_awaiting_info' => 'Awaiting info',
    'status_processing' => 'Processing',
    
    // Actions
    'view' => 'View',
    'edit' => 'Edit',
    'delete' => 'Delete',
    'submit' => 'Submit',
    'cancel' => 'Cancel',
    'save' => 'Save',
    'save_changes' => 'Save changes',
    'back' => 'Back',
    'back_to_dashboard' => 'Back to dashboard',
    'search' => 'Search',
    'filter' => 'Filter',
    'reset' => 'Reset',
    'close' => 'Close',
    'add_comment' => 'Add a comment',
    'send' => 'Send',
    'attach_file' => 'Attach a file',
    'optional' => 'Optional',
    'required' => 'Required',
    
    // Claim details
    'claim_detail_title' => 'Claim Details',
    'claim_info' => 'Information',
    'submitted_on' => 'Submitted on',
    'last_update' => 'Last update',
    'current_status' => 'Current status',
    'full_description' => 'Full description',
    'attached_file' => 'Attached file',
    'download' => 'Download',
    'comments_history' => 'Comments history',
    'no_comments' => 'No comments yet',
    'your_comment' => 'Your comment',
    'comment_placeholder' => 'Write your comment here...',
    'claim_closed_no_comment' => 'This claim is closed. You can no longer add comments.',
    'by' => 'by',
    'you' => 'You',
    'manager' => 'Manager',
    'admin' => 'Administrator',
    
    // Notifications
    'notifications_title' => 'Notifications',
    'mark_all_read' => 'Mark all as read',
    'mark_as_read' => 'Mark as read',
    'unread' => 'Unread',
    'read' => 'Read',
    'new_comment' => 'New comment',
    'status_changed' => 'Status changed',
    'claim_assigned' => 'Claim assigned',
    'claim_closed' => 'Claim closed',
    'notif_status_changed_title' => 'Status changed',
    'notif_status_changed_message' => 'Your claim status is now',
    'notif_comment_added_title' => 'New comment',
    'status_soumis' => 'Submitted',
    'status_en_cours' => 'In Progress',
    'status_en_cours_de_traitement' => 'Processing',
    'status_en_attente' => 'Pending',
    'status_resolu' => 'Resolved',
    'status_rejete' => 'Rejected',
    'status_archive' => 'Archived',
    'status_traite' => 'Processed',
    'status_ferme' => 'Closed',
    'status_attente_info' => 'Awaiting info',
    'your_claim' => 'Your claim',
    'notif_comment_added_message' => 'A new comment has been added to your claim',
    'system_status_change_comment' => 'Status has been changed to',
    'no_notifications_yet' => 'No notifications yet',
    'stay_tuned' => 'You will be notified of any updates regarding your claims.',
    'notif_see_all' => 'See all notifications',
    'notif_no_notifications' => 'No notifications',
    
    // Profile
    'profile_title' => 'My Profile',
    'personal_info' => 'Personal information',
    'account_security' => 'Account security',
    'first_name' => 'First name',
    'last_name' => 'Last name',
    'email_address' => 'Email address',
    'current_password' => 'Current password',
    'new_password' => 'New password',
    'confirm_new_password' => 'Confirm new password',
    'update_profile' => 'Update profile',
    'update_password' => 'Change password',
    'profile_updated' => 'Profile updated successfully!',
    'password_updated' => 'Password changed successfully!',
    'all_fields_required' => 'All fields are required.',
    'email_invalid' => 'The email address is invalid.',
    'email_already_used' => 'This email address is already in use.',
    'password_incorrect' => 'The current password is incorrect.',
    'update_error' => 'Update error.',
    
    // Submission
    'submit_claim_title' => 'New Claim',
    'claim_form' => 'Claim Form',
    'subject' => 'Claim Subject',
    'subject_placeholder' => 'Ex: Connection problem...',
    'category' => 'Category',
    'select_category' => 'Select a category',
    'choose_category' => 'Choose a category...',
    'description' => 'Detailed Description',
    'description_placeholder' => 'Describe your problem in detail...',
    'supporting_document' => 'Attachment',
    'click_to_upload' => 'Click to upload',
    'or_drag_drop' => 'or drag and drop',
    'file_types_max_size' => 'JPG, PNG, PDF, DOC (Max 5 MB)',
    'view_my_claims' => 'View my claims',
    'error_occurred' => 'An error occurred',
    'supporting_document_help' => 'Accepted formats: PDF, JPG, PNG, DOCX (max 5MB)',
    'choose_file' => 'Choose file',
    'no_file_chosen' => 'No file chosen',
    'submit_claim_button' => 'Submit claim',
    'claim_submitted' => 'Claim submitted successfully!',
    'claim_number' => 'Claim number',
    'claim_tracked' => 'You can track its progress in your dashboard.',
    'submit_another' => 'Submit another claim',
    'fill_required_fields' => 'Please fill in all required fields.',
    'file_too_large' => 'File is too large (max 5MB).',
    'invalid_file_type' => 'Unauthorized file type.',
    
    // Messages
    'success' => 'Success',
    'error' => 'Error',
    'warning' => 'Warning',
    'info' => 'Information',
    'no_results' => 'No results',
    'loading' => 'Loading...',
    
    // Footer
    'footer_rights' => 'All rights reserved',
    'footer_contact' => 'Contact',
    'footer_about' => 'About',
    'footer_terms' => 'Terms of Use',
    'footer_privacy' => 'Privacy Policy',
];
